apiVersion: v1
kind: Service
metadata:
  name: collegeblackjacktour
spec:
  type: web
  regions:
    - was
  scaling:
    min: 1
    max: 1
  instance_types:
    - nano
  env:
    - key: NODE_ENV
      value: production
  ports:
    - port: 8000
      protocol: http
  routes:
    - path: /
  build:
    type: buildpack
    buildCommand: npm ci && npm run build
    runCommand: npm run start
  healthChecks:
    - path: /
      port: 8000
      protocol: http