apiVersion: v1
kind: Service
metadata:
  name: collegeblackjacktour
spec:
  type: web
  regions:
    - was
  scaling:
    min: 1
    max: 1
  instance_types:
    - nano
  env:
    - key: NODE_ENV
      value: production
    - key: PORT
      value: "8000"
  ports:
    - port: 8000
      protocol: http
  routes:
    - path: /
  git:
    branch: main
  build:
    type: buildpack
    buildCommand: npm ci && npm run build
    runCommand: npm start
  healthChecks:
    - path: /
      port: 8000
      protocol: http
      interval: 30
      timeout: 5
      gracePeriod: 60