export const collegeNames = [
  "Abilene Christian Wildcats",
  "Air Force Falcons",
  "Akron Zips",
  "Alabama Crimson Tide",
  "Albany Great Danes",
  "American Eagles",
  "Appalachian State Mountaineers",
  "Arizona State Sun Devils",
  "Arizona Wildcats",
  "Arkansas Razorbacks",
  "Arkansas State Red Wolves",
  "Army West Point Black Knights",
  "Auburn Tigers",
  "Austin Peay Governors",
  "BYU Cougars",
  "Ball State Cardinals",
  "Baylor Bears",
  "Bellarmine Knights",
  "Belmont Bruins",
  "Binghamton Bearcats",
  "Boise State Broncos",
  "Boston College Eagles",
  "Boston University Terriers",
  "Bowling Green Falcons",
  "Bradley Braves",
  "Brown Bears",
  "Bryant Bulldogs",
  "Bucknell Bison",
  "Buffalo Bulls",
  "Butler Bulldogs",
  "California Baptist Lancers",
  "California Golden Bears",
  "Campbell Fighting Camels",
  "Canisius Golden Griffins",
  "Central Arkansas Bears",
  "Central Michigan Chippewas",
  "Charleston Southern Buccaneers",
  "Chattanooga Mocs",
  "Cincinnati Bearcats",
  "Citadel Bulldogs",
  "Clemson Tigers",
  "Coastal Carolina Chanticleers",
  "Colgate Raiders",
  "College of Charleston Cougars",
  "Colorado Buffaloes",
  "Colorado State Rams",
  "Columbia Lions",
  "Connecticut Huskies",
  "Cornell Big Red",
  "Creighton Bluejays",
  "Dartmouth Big Green",
  "Davidson Wildcats",
  "Dayton Flyers",
  "DePaul Blue Demons",
  "Delaware Fightin Blue Hens",
  "Denver Pioneers",
  "Drake Bulldogs",
  "Drexel Dragons",
  "Duke Blue Devils",
  "Duquesne Dukes",
  "East Tennessee State Buccaneers",
  "Eastern Kentucky Colonels",
  "Eastern Michigan Eagles",
  "Eastern Washington Eagles",
  "Elon Phoenix",
  "Evansville Purple Aces",
  "Fairfield Stags",
  "Florida Gulf Coast Eagles",
  "Florida Gators",
  "Florida State Seminoles",
  "Fordham Rams",
  "Fresno State Bulldogs",
  "Furman Paladins",
  "Gardner Webb Runnin Bulldogs",
  "George Mason Patriots",
  "George Washington Colonials",
  "Georgetown Hoyas",
  "Georgia Bulldogs",
  "Georgia Southern Eagles",
  "Georgia State Panthers",
  "Georgia Tech Yellow Jackets",
  "Gonzaga Bulldogs",
  "Grand Canyon Antelopes",
  "Hampton Pirates",
  "Harvard Crimson",
  "Hawaii Rainbow Warriors",
  "High Point Panthers",
  "Hofstra Pride",
  "Holy Cross Crusaders",
  "Houston Baptist Huskies",
  "Houston Cougars",
  "Idaho State Bengals",
  "Idaho Vandals",
  "Illinois Chicago UIC Flames",
  "Illinois Fighting Illini",
  "Illinois State Redbirds",
  "Incarnate Word Cardinals",
  "Indiana Hoosiers",
  "Indiana State Sycamores",
  "Iona Gaels",
  "Iowa Hawkeyes",
  "Iowa State Cyclones",
  "Jacksonville Dolphins",
  "James Madison Dukes",
  "Kansas City UMKC Roos",
  "Kansas Jayhawks",
  "Kansas State Wildcats",
  "Kent State Golden Flashes",
  "Kentucky Wildcats",
  "LSU Tigers",
  "La Salle Explorers",
  "Lafayette Leopards",
  "Lamar Cardinals",
  "Lehigh Mountain Hawks",
  "Lipscomb Bisons",
  "Longwood Lancers",
  "Louisiana Lafayette Ragin Cajuns",
  "Louisiana Monroe Warhawks",
  "Louisville Cardinals",
  "Loyola Chicago Ramblers",
  "Loyola Marymount Lions",
  "Loyola University Maryland Greyhounds",
  "Maine Black Bears",
  "Manhattan Jaspers",
  "Marist Red Foxes",
  "Marquette Golden Eagles",
  "Marshall Thundering Herd",
  "Maryland Terrapins",
  "McNeese State Cowboys",
  "Mercer Bears",
  "Miami Hurricanes",
  "Miami OH Redhawks",
  "Michigan State Spartans",
  "Michigan Wolverines",
  "Minnesota Golden Gophers",
  "Mississippi State Bulldogs",
  "Missouri State Bears",
  "Missouri Tigers",
  "Monmouth Hawks",
  "Montana Grizzlies",
  "Montana State Bobcats",
  "Mount St. Marys Mountaineers",
  "Murray State Racers",
  "Navy Midshipmen",
  "Nebraska Cornhuskers",
  "Nebraska Omaha Mavericks",
  "Nevada Wolf Pack",
  "New Hampshire Wildcats",
  "New Jersey Institute of Technology NJIT Highlanders",
  "New Mexico Lobos",
  "New Orleans Privateers",
  "Niagara Purple Eagles",
  "Nicholls State Colonels",
  "North Alabama Lions",
  "North Carolina AT Aggies",
  "North Carolina State Wolfpack",
  "North Carolina Tar Heels",
  "North Dakota Fighting Hawks",
  "North Dakota State Bison",
  "North Florida Ospreys",
  "Northeastern Huskies",
  "Northern Arizona Lumberjacks",
  "Northern Colorado Bears",
  "Northern Illinois Huskies",
  "Northern Iowa Panthers",
  "Northwestern State Demons",
  "Northwestern Wildcats",
  "Notre Dame Fighting Irish",
  "Ohio Bobcats",
  "Ohio State Buckeyes",
  "Oklahoma Sooners",
  "Oklahoma State Cowboys",
  "Old Dominion Monarchs",
  "Ole Miss Rebels",
  "Oral Roberts Golden Eagles",
  "Oregon Ducks",
  "Oregon State Beavers",
  "Pacific Tigers",
  "Penn Quakers",
  "Penn State Nittany Lions",
  "Pepperdine Waves",
  "Pitt Panthers",
  "Portland Pilots",
  "Portland State Vikings",
  "Presbyterian Blue Hose",
  "Princeton Tigers",
  "Providence Friars",
  "Purdue Boilermakers",
  "Queens University of Charlotte Royals",
  "Quinnipiac Bobcats",
  "Radford Highlanders",
  "Rhode Island Rams",
  "Richmond Spiders",
  "Rider Broncs",
  "Rutgers Scarlet Knights",
  "SMU Mustang",
  "Sacramento State Hornets",
  "Saint Josephs Hawks",
  "Saint Louis Billikens",
  "Saint Marys College Gaels",
  "Saint Peters Peacocks",
  "Samford Bulldogs",
  "San Diego State Aztecs",
  "San Diego Toreros",
  "San Francisco Dons",
  "San Jose State Spartans",
  "Santa Clara Broncos",
  "Seattle Redhawks",
  "Seton Hall Pirates",
  "Siena Saints",
  "South Alabama Jaguars",
  "South Carolina Gamecocks",
  "South Carolina Upstate Spartans",
  "South Dakota Coyotes",
  "South Dakota State Jackrabbits",
  "Southeastern Louisiana Lions",
  "Southern Illinois Salukis",
  "Southern Miss Golden Eagles",
  "Southern Utah Thunderbirds",
  "St. Bonaventure Bonnies",
  "St. Johns Red Storm",
  "St. Thomas Tommies",
  "Stanford Cardinal",
  "Stephen F. Austin Lumberjacks",
  "Stetson Hatters",
  "Stony Brook Seawolves",
  "Syracuse Orange",
  "TCU Horned Frogs",
  "Tarleton State Texans",
  "Tennessee Volunteers",
  "Texas AM Commerce Lions",
  "Texas AM Corpus Christi Islanders",
  "Texas AM University",
  "Texas Longhorns",
  "Texas Rio Grande Valley UTRGV Vaqueros",
  "Texas State Bobcats",
  "Texas Tech Red Raiders",
  "Toledo Rockets",
  "Towson Tigers",
  "Troy Trojans",
  "UCF Knights",
  "UCLA Bruins",
  "UMass Amherst Minutemen",
  "UMass Lowell River Hawks",
  "UNC Asheville Bulldogs",
  "UNC Wilmington Seahawks",
  "UNCG Spartans",
  "UNLV Rebels",
  "USC Trojans",
  "UT Arlington Mavericks",
  "University of Maryland Baltimore County UMBC Retrievers",
  "Utah State Aggies",
  "Utah Tech Trailblazers",
  "Utah Utes",
  "Utah Valley Wolverines",
  "VCU Rams",
  "VMI Keydets",
  "Valparaiso Beacons",
  "Vanderbilt Commodores",
  "Vermont Catamounts",
  "Villanova Wildcats",
  "Virginia Cavaliers",
  "Virginia Tech Hokies",
  "Wake Forest Demon Deacons",
  "Washington Huskies",
  "Washington State Cougars",
  "Weber State Wildcats",
  "West Virginia Mountaineers",
  "Western Carolina Catamounts",
  "Western Illinois Leathernecks",
  "Western Michigan Broncos",
  "William Mary Tribe",
  "Winthrop Eagles",
  "Wisconsin Badgers",
  "Wofford Terriers",
  "Wyoming Cowboys",
  "Xavier Musketeers",
  "Yale Bulldogs",
  "West Georgia Wolves"
];
