export const CONFERENCE_DATA = {
  'America East Conference': [
    'Albany Great Danes',
    'Binghamton Bearcats',
    'Maine Black Bears',
    'University of Maryland Baltimore County UMBC Retrievers',
    'UMass Lowell River Hawks',
    'New Hampshire Wildcats',
    'New Jersey Institute of Technology NJIT Highlanders',
    'Bryant Bulldogs',
    'Vermont Catamounts'
  ],
  'Atlantic 10 Conference': [
    'Davidson Wildcats',
    'Dayton Flyers',
    'Duquesne Dukes',
    'Fordham Rams',
    'George Mason Patriots',
    'George Washington Colonials',
    'La Salle Explorers',
    'Loyola Chicago Ramblers',
    'UMass Amherst Minutemen',
    'Rhode Island Rams',
    'Richmond Spiders',
    'Saint Josephs Hawks',
    'Saint Louis Billikens',
    'St. Bonaventure Bonnies',
    'VCU Rams'
  ],
  'Atlantic Coast Conference': [
    'Boston College Eagles',
    'Clemson Tigers',
    'Duke Blue Devils',
    'Florida State Seminoles',
    'Georgia Tech Yellow Jackets',
    'Louisville Cardinals',
    'Miami Hurricanes',
    'North Carolina State Wolfpack',
    'North Carolina Tar Heels',
    'Notre Dame Fighting Irish',
    'Pitt Panthers',
    'Syracuse Orange',
    'Virginia Cavaliers',
    'Virginia Tech Hokies',
    'Wake Forest Demon Deacons'
  ],
  'Atlantic Sun Conference (ASUN)': [
    'Austin Peay Governors',
    'Bellarmine Knights',
    'Central Arkansas Bears',
    'Eastern Kentucky Colonels',
    'Florida Gulf Coast Eagles',
    'Jacksonville Dolphins',
    'Lipscomb Bisons',
    'North Alabama Lions',
    'North Florida Ospreys',
    'Queens University of Charlotte Royals',
    'Stetson Hatters'
  ],
  'Big East Conference': [
    'Butler Bulldogs',
    'Connecticut Huskies',
    'Creighton Bluejays',
    'DePaul Blue Demons',
    'Georgetown Hoyas',
    'Marquette Golden Eagles',
    'Providence Friars',
    'Seton Hall Pirates',
    'St. Johns Red Storm',
    'Villanova Wildcats',
    'Xavier Musketeers'
  ],
  'Big Sky Conference': [
    'Eastern Washington Eagles',
    'Idaho State Bengals',
    'Idaho Vandals',
    'Montana Grizzlies',
    'Montana State Bobcats',
    'Northern Arizona Lumberjacks',
    'Northern Colorado Bears',
    'Portland State Vikings',
    'Sacramento State Hornets',
    'Weber State Wildcats'
  ],
  'Big South Conference': [
    'Campbell Fighting Camels',
    'Charleston Southern Buccaneers',
    'Gardner Webb Runnin Bulldogs',
    'High Point Panthers',
    'Longwood Lancers',
    'Presbyterian Blue Hose',
    'Radford Highlanders',
    'South Carolina Upstate Spartans',
    'UNC Asheville Bulldogs',
    'Winthrop Eagles'
  ],
  'Big 12 Conference': [
    'Baylor Bears',
    'BYU Cougars',
    'Cincinnati Bearcats',
    'Colorado Buffaloes',
    'Houston Cougars',
    'Iowa State Cyclones',
    'Kansas Jayhawks',
    'Kansas State Wildcats',
    'Oklahoma State Cowboys',
    'TCU Horned Frogs',
    'Texas Tech Red Raiders',
    'UCF Knights',
    'Utah Utes',
    'West Virginia Mountaineers'
  ],
  'Big Ten Conference': [
    'Illinois Fighting Illini',
    'Indiana Hoosiers',
    'Iowa Hawkeyes',
    'Maryland Terrapins',
    'Michigan State Spartans',
    'Michigan Wolverines',
    'Minnesota Golden Gophers',
    'Nebraska Cornhuskers',
    'Northwestern Wildcats',
    'Ohio State Buckeyes',
    'Oregon Ducks',
    'Penn State Nittany Lions',
    'Purdue Boilermakers',
    'Rutgers Scarlet Knights',
    'UCLA Bruins',
    'USC Trojans',
    'Washington Huskies',
    'Wisconsin Badgers'
  ],
  'Colonial Athletic Association': [
    'Delaware Fightin Blue Hens',
    'Drexel Dragons',
    'Elon Phoenix',
    'Hampton Pirates',
    'Hofstra Pride',
    'Monmouth Hawks',
    'North Carolina AT Aggies',
    'Northeastern Huskies',
    'Stony Brook Seawolves',
    'Towson Tigers',
    'UNC Wilmington Seahawks',
    'William Mary Tribe'
  ],
  'Ivy League': [
    'Brown Bears',
    'Columbia Lions',
    'Cornell Big Red',
    'Dartmouth Big Green',
    'Harvard Crimson',
    'Penn Quakers',
    'Princeton Tigers',
    'Yale Bulldogs'
  ],
  'Metro Atlantic Athletic Conference (MAAC)': [
    'Canisius Golden Griffins',
    'Fairfield Stags',
    'Iona Gaels',
    'Manhattan Jaspers',
    'Marist Red Foxes',
    'Mount St. Marys Mountaineers',
    'Niagara Purple Eagles',
    'Quinnipiac Bobcats',
    'Rider Broncs',
    'Saint Peters Peacocks',
    'Siena Saints'
  ],
  'Mid-American Conference': [
    'Akron Zips',
    'Ball State Cardinals',
    'Bowling Green Falcons',
    'Buffalo Bulls',
    'Central Michigan Chippewas',
    'Eastern Michigan Eagles',
    'Kent State Golden Flashes',
    'Miami OH RedHawks',
    'Northern Illinois Huskies',
    'Ohio Bobcats',
    'Toledo Rockets',
    'Western Michigan Broncos'
  ],
  'Missouri Valley Conference': [
    'Belmont Bruins',
    'Bradley Braves',
    'Drake Bulldogs',
    'Evansville Purple Aces',
    'Illinois State Redbirds',
    'Indiana State Sycamores',
    'Missouri State Bears',
    'Murray State Racers',
    'Northern Iowa Panthers',
    'Southern Illinois Salukis',
    'UIC Flames',
    'Valparaiso Beacons'
  ],
  'Mountain West Conference': [
    'Air Force Falcons',
    'Boise State Broncos',
    'Colorado State Rams',
    'Fresno State Bulldogs',
    'Nevada Wolf Pack',
    'New Mexico Lobos',
    'San Diego State Aztecs',
    'San Jose State Spartans',
    'UNLV Rebels',
    'Utah State Aggies',
    'Wyoming Cowboys'
  ],
  'Pac-12 Conference': [
    'Arizona State Sun Devils',
    'Arizona Wildcats',
    'California Golden Bears',
    'Oregon State Beavers',
    'Stanford Cardinal',
    'Washington State Cougars'
  ],
  'Patriot League Conference': [
    'American Eagles',
    'Army Black Knights',
    'Boston University Terriers',
    'Bucknell Bison',
    'Colgate Raiders',
    'Holy Cross Crusaders',
    'Lafayette Leopards',
    'Lehigh Mountain Hawks',
    'Loyola Maryland Greyhounds',
    'Navy Midshipmen'
  ],
  'Southeastern Conference': [
    'Alabama Crimson Tide',
    'Arkansas Razorbacks',
    'Auburn Tigers',
    'Florida Gators',
    'Georgia Bulldogs',
    'Kentucky Wildcats',
    'LSU Tigers',
    'Mississippi State Bulldogs',
    'Missouri Tigers',
    'Ole Miss Rebels',
    'Oklahoma Sooners',
    'South Carolina Gamecocks',
    'Tennessee Volunteers',
    'Texas AM Aggies',
    'Texas Longhorns',
    'Vanderbilt Commodores'
  ],
  'Southern Conference': [
    'Chattanooga Mocs',
    'East Tennessee State Buccaneers',
    'Furman Paladins',
    'Mercer Bears',
    'Samford Bulldogs',
    'The Citadel Bulldogs',
    'UNCG Spartans',
    'VMI Keydets',
    'Western Carolina Catamounts',
    'Wofford Terriers'
  ],
  'Southland Conference': [
    'Houston Christian Huskies',
    'Incarnate Word Cardinals',
    'Lamar Cardinals',
    'McNeese State Cowboys',
    'New Orleans Privateers',
    'Nicholls State Colonels',
    'Northwestern State Demons',
    'Southeastern Louisiana Lions',
    'Texas AM Commerce Lions',
    'Texas AM Corpus Christi Islanders'
  ],
  'Summit League': [
    'Denver Pioneers',
    'Kansas City UMKC Roos',
    'North Dakota Fighting Hawks',
    'North Dakota State Bison',
    'Nebraska Omaha Mavericks',
    'Oral Roberts Golden Eagles',
    'South Dakota Coyotes',
    'South Dakota State Jackrabbits',
    'St. Thomas Tommies',
    'Western Illinois Leathernecks'
  ],
  'Sun Belt Conference': [
    'Appalachian State Mountaineers',
    'Arkansas State Red Wolves',
    'Coastal Carolina Chanticleers',
    'Georgia Southern Eagles',
    'Georgia State Panthers',
    'James Madison Dukes',
    'Louisiana Lafayette Ragin Cajuns',
    'Louisiana Monroe Warhawks',
    'Marshall Thundering Herd',
    'Old Dominion Monarchs',
    'South Alabama Jaguars',
    'Southern Miss Golden Eagles',
    'Texas State Bobcats',
    'Troy Trojans'
  ],
  'West Coast Conference': [
    'Gonzaga Bulldogs',
    'Loyola Marymount Lions',
    'Pacific Tigers',
    'Pepperdine Waves',
    'Portland Pilots',
    'Saint Marys College Gaels',
    'San Diego Toreros',
    'San Francisco Dons',
    'Santa Clara Broncos'
  ],
  'Western Athletic Conference': [
    'Abilene Christian Wildcats',
    'California Baptist Lancers',
    'Grand Canyon Antelopes',
    'Seattle Redhawks',
    'Southern Utah Thunderbirds',
    'Stephen F. Austin Lumberjacks',
    'Tarleton State Texans',
    'UT Arlington Mavericks',
    'UT Rio Grande Valley UTRGV Vaqueros',
    'Utah Tech Trailblazers',
    'Utah Valley Wolverines'
  ]
};

export const CONFERENCE_NAMES = {
  'America_East_Conference': 'America East Conference',
  'Atlantic_10_Conference': 'Atlantic 10 Conference',
  'Atlantic_Coast_Conference': 'Atlantic Coast Conference',
  'Atlantic_Sun_Conference_ASUN': 'Atlantic Sun Conference (ASUN)',
  'Big_East_Conference': 'Big East Conference',
  'Big_Sky_Conference': 'Big Sky Conference',
  'Big_South_Conference': 'Big South Conference',
  'Big_12_Conference': 'Big 12 Conference',
  'Big_Ten_Conference': 'Big Ten Conference',
  'Colonial_Athletic_Association': 'Colonial Athletic Association',
  'Ivy_League': 'Ivy League',
  'Metro_Atlantic_Athletic_Conference_MAAC': 'Metro Atlantic Athletic Conference (MAAC)',
  'Mid_American_Conference': 'Mid-American Conference',
  'Missouri_Valley_Conference': 'Missouri Valley Conference',
  'Mountain_West_Conference': 'Mountain West Conference',
  'Pac_12_Conference': 'Pac-12 Conference',
  'Patriot_League_Conference': 'Patriot League Conference',
  'Southeastern_Conference': 'Southeastern Conference',
  'Southern_Conference': 'Southern Conference',
  'Southland_Conference': 'Southland Conference',
  'Summit_League': 'Summit League',
  'Sun_Belt_Conference': 'Sun Belt Conference',
  'West_Coast_Conference': 'West Coast Conference',
  'Western_Athletic_Conference': 'Western Athletic Conference'
};
